config/routes.rb
Rails.application.routes.draw do
  
  resources :logins do
     resources :details
  end
  resources :details
   root "logins#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/detail.rb
class Login < ApplicationRecord
    belongs_to :login
end

app/models/login.rb
class Login < ApplicationRecord
    validates :username ,presence: true
    has_many :detail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :set_detail, only: %i[ show edit update destroy ]

  # GET /details or /details.json
  def index
    @u=Login.find(1)
    @detail=@u.Detail.all
  end

  # GET /details/1 or /details/1.json
  def show
    @login=Login.all
    @login.Detail.find(params[:id])
  end

  # GET /details/new
  def new
    @detail = Detail.new
  end

  # GET /details/1/edit
  def edit
  end

  # POST /details or /details.json
  def create
    # @detail = Detail.new(detail_params)
    @detail=Detail.create(number: params[:number],city: params[:city],state: params, login_id: @login.id)
    
    @detail.save
    # respond_to do |format|
    #   if @detail.save
    #     format.html { redirect_to detail_url(@detail), notice: "Detail was successfully created." }
    #     format.json { render :show, status: :created, location: @detail }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @detail.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /details/1 or /details/1.json
  def update
    respond_to do |format|
      if @detail.update(detail_params)
        format.html { redirect_to detail_url(@detail), notice: "Detail was successfully updated." }
        format.json { render :show, status: :ok, location: @detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /details/1 or /details/1.json
  def destroy
    @detail.destroy

    respond_to do |format|
      format.html { redirect_to details_url, notice: "Detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detail
      @detail = Detail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def detail_params
      params.require(:detail).permit(:number, :city, :state)
    end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  # http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
  before_action :set_login, only: %i[ show edit update destroy ]

  # GET /logins or /logins.json
  def index
    
    @logins = Login.all
  end

  # GET /logins/1 or /logins/1.json
  def show
    @xy=Login.all
  end

  # GET /logins/new
  def new
    @login = Login.new
  end

  # GET /logins/1/edit
  def edit
  end
  def loginx


    @login =Login.all
  end
  # POST /logins or /logins.json
  def create
    @login = Login.new(login_params)

    respond_to do |format|
      if @login.save
        format.html { redirect_to login_url(@login), notice: "Login was successfully created." }
        format.json { render :show, status: :created, location: @login }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logins/1 or /logins/1.json
  def update
    respond_to do |format|
      if @login.update(login_params)
        format.html { redirect_to login_url(@login), notice: "Login was successfully updated." }
        format.json { render :show, status: :ok, location: @login }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logins/1 or /logins/1.json
  def destroy
    @login.destroy

    respond_to do |format|
      format.html { redirect_to logins_url, notice: "Login was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login
      @login = Login.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def login_params
      params.require(:login).permit(:username, :password)
    end

  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/details/_detail.html.erb
<div id="<%= dom_id detail %>">
  <p>
    <strong>Number:</strong>
    <%= detail.number %>
  </p>

  <p>
    <strong>City:</strong>
    <%= detail.city %>
  </p>

  <p>
    <strong>State:</strong>
    <%= detail.state %>
  </p>

</div>

app/views/details/_form.html.erb
<%= form_with(model: detail) do |form| %>
  <% if detail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(detail.errors.count, "error") %> prohibited this detail from being saved:</h2>

      <ul>
        <% detail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.number_field :number %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.text_field :state %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/details/edit.html.erb
<h1>Editing detail</h1>

<%= render "form", detail: @detail %>

<br>

<div>
  <%= link_to "Show this detail", @detail %> |
  <%= link_to "Back to details", details_path %>
</div>

app/views/details/index.html.erb
<%# <p style="color: green"><%= notice %></p>

<h1>Details</h1>

<div id="details">
   <% @detail.each do |detail| %>
    <%= render detail %>
    <p>
      <%= link_to "Show this detail", detail %>
    </p>
  <% end %>
</div>

<%= link_to "New detail", new_detail_path %>

app/views/details/new.html.erb
<h1>New detail</h1>

<%= render "form", detail: @detail %>

<br>

<div>
  <%= link_to "Back to details", details_path %>
</div>

app/views/details/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @detail %>

<div>
  <%= link_to "Edit this detail", edit_detail_path(@detail) %> |
  <%= link_to "Back to details", details_path %>

  <%= button_to "Destroy this detail", @detail, method: :delete %>
</div>

app/views/layouts/application.html.erb
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="stylesheet.css">
    <title style="font-family:brush script mt;">H&M</title>
    <link rel="icon" href="icon.jpg">
    <%= stylesheet_link_tag "application"  %>
    <%= favicon_link_tag 'favicon.png'%>
    
     <%# <script src="java.js" ></script> %>
</head>
<body>
    <div id="logo">
     <%= image_tag "favicon.png" ,class: "logo",id: "logo"%></div> 
    <%#  <img id="logo" src="logo.png"> %>
    <p id="tagline" ><%= link_to "The makers of happy and merry" , new_login_path%></p>
    
   <div id="login">
   <%=link_to "LOGIN" , new_login_path%>
      <%=link_to "HOME" ,@login%>
    </div>
    <hr>

    <div id="menu" ><UL ID="QQ">
        <DIV > </DIV><LI ID="Q6">MENS</LI>
        <LI ID="Q6">WOMEN</LI>
        <LI ID="Q6">BOYS</LI>
        <LI ID="Q6">GIRLS</LI>
        <LI ID="Q6">ACCESSORIES</LI>
        <LI ID="Q6">TREND</LI>
        <LI ID="Q6">NEWEST ARRIVAL</LI></DIV>

        <br>


        <%=yield%>


        <br>
        <br>
           <%= image_tag "1.jpg" ,height: "70%"  ,style:"margin-left:23%"%>
            <!-- <img src="2.jpg" style="width:100%">
            # <img src="3.jpg" style="width:100%">
            #  -->
             <br><br><br>
            <%# <button id="xx" onclick="switchx()"><img  id="image1" src="1.jpg" class="center" style="  width:70%"></button> %>
   
            <%# <%= button_tag image_tag "1.jpg" , link_to 'switchx()'%> %>
        </body>

<footer id="footerx">
     
    <ul>SHOP 
        
      <li>Ladies</li>
      <li>Men</li>
      <li>BAby</li>
      <li>Kids</li>
    </ul>
    <ul>SHOP 
       
      <li>Ladies</li>
      <li>Men</li>
      <li>BAby</li>
      <li>Kids</li>
    </ul>
    <ul>SHOP 
        
      <li>Ladies</li>
      <li>Men</li>
      <li>BAby</li>
      <li>Kids</li>
    </ul>
    
</footer>
</html>

app/views/logins/_form.html.erb
<%= form_with(model: login) do |form| %>
  <% if login.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
        <% login.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div id="form">
  <div  >
    <%= form.label :username, style: "display: block"  ,class: "formuser" %>
    <%= form.text_field :username , style: "margin-left:47%; margin-top:-7px;" %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" ,class: "formuser"%>
    <%= form.text_field :password , style: "margin-left:47% ; margin-top:-7px;"%>
  </div>

  <div>
    <%= form.submit id:"button" %>
  </div>
  </div>
<% end %>

app/views/logins/_login.html.erb
<div id="<%= dom_id login %>">
  <p>
    <strong>Username:</strong>
    <%= login.username %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= login.password %>
  </p>

</div>

app/views/logins/edit.html.erb
<h1 style="text-align:center;">Edit Login Details </h1>

<%= render "form", login: @login %>

<br>

<div id="edit">
  <%= link_to "Show this login", @login %> |
  <%= link_to "Back to logins", logins_path %>
</div>

app/views/logins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 style="color:red; text-align:center;">Logins</h1>

<h5></h5>
<div id="logins" >



  <% @logins.each do |login| %>
    
    <table>
     <th>ID</th>
     <th>USERNAME</th>
     <th>PASSWORD</th>
     <th>SHOW MORE</th>
    </tr>
    <td><%=login.id%></td>
    <td><%= login.username  %></td>
    <td><%= login.password %></td>
    <td><%= link_to "DISPLAY", login %></td>
    </tr>
    </table>
  <% end %>
</div>
<div id="edit">
<%= link_to "New login", new_login_path %></div>

app/views/logins/loginx.html.erb
<%@login.each do |t|%>
<%= render t%>

app/views/logins/new.html.erb
<br>
<h1 style="text-align:center;">LOGIN</h1>

<%= render "form", login: @login  ,id:"hii"%>

<br>

<div>
  <%= link_to "Back to logins", logins_path ,style: "text-align:center; margin-left:48%;"  %>
</div>

app/views/logins/show.html.erb
<p style="color: green"><%= notice %></p>
<div id="show">
<%= render @login %>
<%render @xy%>
<div>
  <%= link_to "Edit this login", edit_login_path(@login) %> 
  <%= link_to "Back to logins"%>
  <div style="color:red;">
  <%= button_to "Destroy this login", @login, method: :delete %></div>
</div>
</div>